# Maria Fisher - Lab 4

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/giswqs/geog-510/blob/main/book/labs/lab_04.ipynb)

## Exercise 1: Variable Assignment and Basic Operations

Create variables to store the following geospatial data:

- The latitude and longitude of New York City: 40.7128, -74.0060.
- The population of New York City: 8,336,817.
- The area of New York City in square kilometers: 783.8.

Perform the following tasks:

1. Calculate and print the population density of New York City (population per square kilometer).
2. Print the coordinates in the format "Latitude: [latitude], Longitude: [longitude]".

In [ ]:
# Store the following geospatial data
latitude_nyc = 40.7128
longitude_nyc = -74.0060
population_nyc = 8336817
area_nyc_km2 = 783.8

#Perform the following tasks:

# Calculate population density
population_density = population_nyc / area_nyc_km2

# Print the results
population_density = f"The population density per square kilometer of NY is:{population_density}"
coordinates = f"Latitude: {latitude_nyc}, Longitude: {longitude_nyc}"

population_density, coordinates


(' The population density per square kilometer of NY is:10636.408522582293',
 'Latitude: 40.7128, Longitude: -74.006')

## Exercise 2: Working with Strings

Create a string variable to store the name of a city, such as "San Francisco". Perform the following operations:

1. Convert the string to lowercase and print the result.
2. Convert the string to uppercase and print the result.
3. Replace "San" with "Los" in the city name and print the new string.

In [ ]:
# String variable to store the name of a city,
city_name = "San Francisco"

# 1.Convert the string to lowercase and print the result.
city_lowercase = city_name.lower()

# 2. Convert the string to uppercase and print the result.
city_uppercase = city_name.upper()

# 3. Replace "San" with "Los" in the city name
city_modified = city_name.replace("San", "Los")

# Print the new string
city_lowercase, city_uppercase, city_modified


('san francisco', 'SAN FRANCISCO', 'Los Francisco')

## Exercise 3: Using Lists

Create a list of tuples, where each tuple contains the name of a city and its corresponding latitude and longitude:

- New York City: (40.7128, -74.0060)
- Los Angeles: (34.0522, -118.2437)
- Chicago: (41.8781, -87.6298)

Perform the following tasks:

1. Add a new city (e.g., Miami: (25.7617, -80.1918)) to the list.
2. Print the entire list of cities.
3. Slice the list to print only the first two cities.

In [ ]:
# Creating the list of tuples with city names and coordinates
cities = [
    ("New York City", 40.7128, -74.0060),
    ("Los Angeles", 34.0522, -118.2437),
    ("Chicago", 41.8781, -87.6298)
]

# 1. Add a new city (São Paulo, Brazil)
cities.append(("São Paulo", -23.5505, -46.6333))

# 2. Print the entire list of cities
cities_list = cities

# 3. Slice the list to print only the first two cities
first_two_cities = cities[:2]

cities_list, first_two_cities


([('New York City', 40.7128, -74.006),
  ('Los Angeles', 34.0522, -118.2437),
  ('Chicago', 41.8781, -87.6298),
  ('São Paulo', -23.5505, -46.6333)],
 [('New York City', 40.7128, -74.006), ('Los Angeles', 34.0522, -118.2437)])

## Exercise 4: Using Tuples

Create a tuple to store the coordinates (latitude, longitude) of the Eiffel Tower: (48.8584, 2.2945). Perform the following tasks:

1. Access and print the latitude and longitude values from the tuple.
2. Try to change the latitude value to 48.8585. What happens? Explain why.

In [ ]:
# Creating the tuple to store the coordinates of the Eiffel Tower
eiffel_tower_coordinates = (48.8584, 2.2945)

## Perform the following tasks:

# 1. Access and print the latitude and longitude values from the tuple
latitude, longitude = eiffel_tower_coordinates

# 2. Try to change the latitude value to 48.8585.
try:
    eiffel_tower_coordinates[0] = 48.8585
except TypeError as e:
    error_message = str(e)

latitude, longitude, error_message if 'error_message' in locals() else None


(48.8584, 2.2945, "'tuple' object does not support item assignment")

### What happens?
 error message : "'tuple' object does not support item assignment"

### Explain why.
tuples in Python are immutable, meaning their values cannot be changed once they are created.

## Exercise 5: Working with Sets

Create a set of countries you have visited, such as {"USA", "France", "Germany"}. Perform the following tasks:

1. Add a new country to the set.
2. Try to add the same country again. What happens?
3. Print the updated set.

In [ ]:
# Create a set of countries you have visited
visited_countries = {"Morocco", "France", "Peru"}

# Perform the following tasks:

# 1. Add a new country to the set
visited_countries.add("Japan")

# 3. Print the set
visited_countries


{'France', 'Japan', 'Morocco', 'Peru'}

In [ ]:
# 2. Try to add the same country again
visited_countries.add("Japan")

In [ ]:
# 3. Printing the updated set
visited_countries

{'France', 'Japan', 'Morocco', 'Peru'}

### What happens?
Nothing, because in Python, sets automatically handle duplicates by ignoring repeated entries.

## Exercise 6: Working with Dictionaries

Create a dictionary to store information about a specific geospatial feature, such as a river:

- Name: "Amazon River"
- Length: 6400 km
- Countries: ["Brazil", "Peru", "Colombia"]

Perform the following tasks:

1. Add a new key-value pair to the dictionary to store the river's average discharge (e.g., 209,000 m³/s).
2. Update the length of the river to 6992 km.
3. Print the dictionary.

In [ ]:
# Create a dictionary to store information about the Amazon River
amazon_river = {
    "Name": "Amazon River",
    "Length_km": 6400,
    "Countries": ["Brazil", "Peru", "Colombia"]
}

# Perform the following tasks:

# 1. Add a new key-value pair to the dictionary to store the river's average discharge (e.g., 209,000 m³/s).
amazon_river["Average_Discharge_m3_s"] = 209000

# 2. Update the length of the river to 6992 km.
amazon_river["Length_km"] = 6992

# 3. Print the updated dictionary
amazon_river


{'Name': 'Amazon River',
 'Length_km': 6992,
 'Countries': ['Brazil', 'Peru', 'Colombia'],
 'Average_Discharge_m3_s': 209000}

## Exercise 7: Nested Data Structures

Create a dictionary to represent a city that contains the city's name, population, and coordinates (latitude, longitude):

- Name: "Tokyo"
- Population: 13,515,271
- Coordinates: (35.6895, 139.6917)

Perform the following tasks:

1. Access and print the population of the city.
2. Access and print the city's latitude.
3. Update the population to 14,000,000 and print the updated dictionary.

In [ ]:
# Create a dictionary to represent a city that contains the city's name, population, and coordinates (latitude, longitude):
tokyo = {
    "Name": "Tokyo",
    "Population": 13515271,
    "Coordinates": (35.6895, 139.6917)
}

# Perform the following tasks:

# 1. Access and printing the population of the city
print("Population:", tokyo["Population"])

# 2. Access and print the city's latitude
print("Latitude:", tokyo["Coordinates"][0])

# 3. Update the population to 14,000,000
tokyo["Population"] = 14000000

# Print the updated dictionary
tokyo


Population: 13515271
Latitude: 35.6895


{'Name': 'Tokyo', 'Population': 14000000, 'Coordinates': (35.6895, 139.6917)}

## Exercise 8: List Operations

Given the list of cities from Exercise 3, perform the following operations:

1. Sort the list of cities alphabetically by name.
2. Create a new list that contains only the city names.
3. Remove the last city from the original list and print the updated list.

In [ ]:
#  List of cities from Exercise 3
cities = [
    ("New York City", 40.7128, -74.0060),
    ("Los Angeles", 34.0522, -118.2437),
    ("Chicago", 41.8781, -87.6298)
]

# Perform the following operations:

# 1. Sort the list of cities alphabetically by name
cities_sorted = sorted(cities, key=lambda city: city[0])

# 2. Create a new list that contains only the city names
city_names = [city[0] for city in cities]

# 3. Remove the last city from the original list
cities.pop()

# Print the results
print("Sorted Cities:", cities_sorted)
print("City Names:", city_names)
print("Updated List:", cities)


Sorted Cities: [('Chicago', 41.8781, -87.6298), ('Los Angeles', 34.0522, -118.2437), ('New York City', 40.7128, -74.006)]
City Names: ['New York City', 'Los Angeles', 'Chicago']
Updated List: [('New York City', 40.7128, -74.006), ('Los Angeles', 34.0522, -118.2437)]


## Exercise 9: Dictionary Operations

Using the dictionary from Exercise 6, perform the following tasks:

1. Check if the key "Length" exists in the dictionary.
2. Print all the keys in the dictionary.
3. Print all the values in the dictionary.

In [ ]:
# Using the dictionary from Exercise 6
amazon_river = {
    "Name": "Amazon River",
    "Length_km": 6400,
    "Countries": ["Brazil", "Peru", "Colombia"]
}

# Perform the following tasks:

# 1. Check if the key "Length" exists in the dictionary.
key_exists = "Length" in amazon_river
print("Does 'Length' exist in the dictionary?", key_exists)

# 2. Print all the keys in the dictionary.
print("Keys:", amazon_river.keys())

# 3. Print all the values in the dictionary.
print("Values:", amazon_river.values())


Does 'Length' exist in the dictionary? False
Keys: dict_keys(['Name', 'Length_km', 'Countries'])
Values: dict_values(['Amazon River', 6400, ['Brazil', 'Peru', 'Colombia']])


## Exercise 10: Practical Application

Imagine you have a list of tuples, each representing a location with its name, latitude, and longitude:

In [ ]:
locations = [
    ("Mount Everest", 27.9881, 86.9250),
    ("K2", 35.8808, 76.5155),
    ("Kangchenjunga", 27.7025, 88.1475),
]

Perform the following tasks:

1. Create a new list that contains only the names of the locations.
2. Create a dictionary where the keys are location names and the values are tuples of their coordinates.
3. Print the latitude of "K2" using the dictionary.

In [ ]:
# List of tuples, each representing a location with its name, latitude, and longitude:
locations = [
    ("Mount Everest", 27.9881, 86.9250),
    ("K2", 35.8808, 76.5155),
    ("Kangchenjunga", 27.7025, 88.1475)
]

# Perform the following tasks:

# 1. Create a new list that contains only the names of the locations.
location_names = [location[0] for location in locations]

# 2. Create a dictionary where the keys are location names and the values are tuples of their coordinates.
location_dict = {location[0]: (location[1], location[2]) for location in locations}

# 3. Print the latitude of "K2" using the dictionary.
k2_latitude = location_dict["K2"][0]

# Displaying the results
print("Location Names:", location_names)
print("Location Dictionary:", location_dict)
print("Latitude of K2:", k2_latitude)


Location Names: ['Mount Everest', 'K2', 'Kangchenjunga']
Location Dictionary: {'Mount Everest': (27.9881, 86.925), 'K2': (35.8808, 76.5155), 'Kangchenjunga': (27.7025, 88.1475)}
Latitude of K2: 35.8808


## Exercise 11: Manipulating Geographic Location Strings

- Create a string that represents the name of a geographic feature (e.g., `"Amazon River"`).
- Convert the string to lowercase and then to uppercase.
- Concatenate the string with the name of the country (e.g., `"Brazil"`) to create a full location name.
- Repeat the string three times, separating each repetition with a dash (`-`).

In [ ]:
# 1. Create a string representing the name of a geographic feature
geo_feature = "Amazon River"

# 2. Convert the string to lowercase
geo_feature_lower = geo_feature.lower()

# 3. Convert the string to uppercase
geo_feature_upper = geo_feature.upper()

# 4. Concatenate the string with the name of the country (e.g., "Brazil") to create a full location name.
full_location = geo_feature + ", Brazil"

# 5. Repeat the string three times, separating each repetition with a dash (-).
repeated_feature = " - ".join([geo_feature] * 3)

# Printing results
print("Lowercase:", geo_feature_lower)
print("Uppercase:", geo_feature_upper)
print("Full Location:", full_location)
print("Repeated Feature:", repeated_feature)


Lowercase: amazon river
Uppercase: AMAZON RIVER
Full Location: Amazon River, Brazil
Repeated Feature: Amazon River - Amazon River - Amazon River


## Exercise 12: Extracting and Formatting Coordinates

- Given a string with the format `"latitude, longitude"` (e.g., `"40.7128N, 74.0060W"`), extract the numeric values of latitude and longitude.
- Convert these values to floats and remove the directional indicators (`N`, `S`, `E`, `W`).
- Format the coordinates into a `POINT` WKT string (e.g., `"POINT(-74.0060 40.7128)"`).

In [ ]:
# 1. Given a string with the format "latitude, longitude" (e.g., "40.7128N, 74.0060W")
coordinates = "40.7128N, 74.0060W"

# Extracting latitude and longitude as strings
latitude_str, longitude_str = coordinates.split(", ")

# 2. Remove the directional indicators (N, S, E, W).
latitude = float(latitude_str[:-1])  # Remove the directional character and convert to float
longitude = float(longitude_str[:-1])  # Remove the directional character and convert to float
print(latitude, longitude)

# 3. Format the coordinates into a POINT WKT string (e.g., "POINT(-74.0060 40.7128)")
wkt_point = f"POINT({longitude} {latitude})"
print("WKT POINT:", wkt_point)



40.7128 74.006
WKT POINT: POINT(74.006 40.7128)


## Exercise 13: Building Dynamic SQL Queries

- Given a table name and a condition, dynamically build an SQL query string.
- Example: If `table_name = "cities"` and `condition = "population > 1000000"`, the query should be `"SELECT * FROM cities WHERE population > 1000000;"`.
- Add additional conditions dynamically, like `AND` clauses.

In [ ]:
# 1. Given table name and condition
table_name = "cities"
condition = "population > 1000000"
additional_conditions = ["country = 'USA'", "name LIKE 'blabla'"]

# 2. Dynamically build an SQL query string.
query = f"SELECT * FROM {table_name} WHERE {condition}"

# 3. Add additional conditions dynamically, like AND clauses.
for cond in additional_conditions:
    query += f" AND {cond}"

# 4. End of the query
query += ";"

# Print the result
print(query)




SELECT * FROM cities WHERE population > 1000000 AND country = 'USA' AND name LIKE 'blabla';


## Exercise 14: String Normalization and Cleaning

- Given a list of city names with inconsistent formatting (e.g., `[" new york ", "Los ANGELES", "   CHICAGO"]`), normalize the names by:
  - Stripping any leading or trailing whitespace.
  - Converting them to title case (e.g., `"New York"`, `"Los Angeles"`, `"Chicago"`).
- Ensure that the output is a clean list of city names.

In [ ]:
# 1. Given list of city names with inconsistent formatting
cities = [" new york ", "Los ANGELES", " CHICAGO"]

# 2. Strip any leading or trailing whitespace from each city name
stripped_cities = [city.strip() for city in cities]

# 3. Convert the city names to title case
normalized_cities = [city.title() for city in stripped_cities]

# Print the cleaned list
print(normalized_cities)



['New York', 'Los Angeles', 'Chicago']


## Exercise 15: Parsing and Extracting Address Information

- Given a string in the format `"Street, City, Country"` (e.g., `"123 Main St, Springfield, USA"`), write a function that parses the string into a dictionary with keys `street`, `city`, and `country`.
- The function should return a dictionary like `{"street": "123 Main St", "city": "Springfield", "country": "USA"}`.

In [8]:
# Write a function that parses the string into a dictionary with keys street, city, and country.

def parse_address(address: str) -> dict:
    keys = [keys.strip() for keys in address.split(",")] # split the string by ',' and remove spaces

    # assign each part of the string to a respective key
    return {
        "street": keys[0],
        "city": keys[1],
        "country": keys[2]}

# Given a string in the format:
address = "123 Main St, Springfield, USA"
parsed_address = parse_address(address)
print(parsed_address)


{'street': '123 Main St', 'city': 'Springfield', 'country': 'USA'}


## Exercise 16: Using For Loops to Process Coordinate Lists

- Create a list of tuples representing coordinates (latitude, longitude).
- Write a `for` loop that prints each coordinate and indicates whether it is in the Northern or Southern Hemisphere based on the latitude.

In [10]:
# Create a list of tuples representing coordinates (latitude, longitude).
coordinates = [
    (51.5074, -0.1278),  # London, UK (Northern Hemisphere)
    (41.8781, -87.6298),  # Chicago, USA (Northern Hemisphere)
    (-23.5505, -46.6333),  # São Paulo, Brazil (Southern Hemisphere)
    (-36.8485, 174.7633)  # Auckland, New Zealand (Southern Hemisphere)
]

# Write a for loop that prints each coordinate and indicates whether it is in the Northern or Southern Hemisphere based on the latitude.
for lat, lon in coordinates:
    hemisphere = "Northern Hemisphere" if lat >= 0 else "Southern Hemisphere"
    print(f"Coordinate: ({lat}, {lon}) is in the {hemisphere}.")



Coordinate: (51.5074, -0.1278) is in the Northern Hemisphere.
Coordinate: (41.8781, -87.6298) is in the Northern Hemisphere.
Coordinate: (-23.5505, -46.6333) is in the Southern Hemisphere.
Coordinate: (-36.8485, 174.7633) is in the Southern Hemisphere.


## Exercise 17: While Loops for Iterative Processing

- Create a list of coordinates (latitude, longitude).
- Write a `while` loop that continues to print each coordinate until it encounters a coordinate with a negative latitude.
- Stop the loop once this condition is met.

In [13]:
# Create a list of coordinates (latitude, longitude).
coordinates = [
    (51.5074, -0.1278),  # London, UK (Northern Hemisphere)
    (41.8781, -87.6298),  # Chicago, USA (Northern Hemisphere)
    (-23.5505, -46.6333),  # São Paulo, Brazil (Southern Hemisphere)
    (-36.8485, 174.7633)  # Auckland, New Zealand (Southern Hemisphere)
]

# Initialize index
index = 0

# Write a while loop that continues to print each coordinate until it encounters a coordinate with a negative latitude.
while index < len(coordinates):
    lat, lon = coordinates[index]

    # Stop the loop once this condition is met.
    if lat < 0:
        print("Encountered a coordinate with a negative latitude. Stopping loop.")
        break

    print(f"Coordinate: ({lat}, {lon})")
    index += 1


Coordinate: (51.5074, -0.1278)
Coordinate: (41.8781, -87.6298)
Encountered a coordinate with a negative latitude. Stopping loop.


## Exercise 18: Conditional Logic in Loops

- Create a list of coordinates and use a `for` loop to iterate over them.
- Use an `if-elif-else` statement inside the loop to classify each coordinate based on its longitude:
  - Print `"Eastern Hemisphere"` if the longitude is greater than 0.
  - Print `"Western Hemisphere"` if the longitude is less than 0.

In [20]:
# Create a list of coordinates and use a for loop to iterate over them.
coordinates = [
    (40.7128, -74.0060),  # New York, USA (Western Hemisphere)
    (51.5074, -0.1278),   # London, UK (Western Hemisphere)
    (-33.8688, 151.2093), # Sydney, Australia (Eastern Hemisphere)
    (35.6895, 139.6917),  # Tokyo, Japan (Eastern Hemisphere)
    (0.0, 0.0),           # near the Equator
]

# Use an if-elif-else statement inside the loop to classify each coordinate based on its longitude:
for lat, lon in coordinates:
    if lon > 0:
        print(f"Coordinate: ({lat}, {lon}) is in the Eastern Hemisphere.")
    elif lon < 0:
        print(f"Coordinate: ({lat}, {lon}) is in the Western Hemisphere.")
    else:
        print(f"Coordinate: ({lat}, {lon}) is near the Equator.")


Coordinate: (40.7128, -74.006) is in the Western Hemisphere.
Coordinate: (51.5074, -0.1278) is in the Western Hemisphere.
Coordinate: (-33.8688, 151.2093) is in the Eastern Hemisphere.
Coordinate: (35.6895, 139.6917) is in the Eastern Hemisphere.
Coordinate: (0.0, 0.0) is near the Equator.


## Exercise 19: Filtering Data with Combined Loops and Conditionals

- Given a list of coordinates, filter out and store only those located in the Southern Hemisphere (latitude < 0).
- Count the number of coordinates that meet this condition and print the result.

In [22]:
# Given a list of coordinates.
coordinates = [
    (40.7128, -74.0060),  # New York, USA (Northern Hemisphere)
    (51.5074, -0.1278),   # London, UK (Northern Hemisphere)
    (35.6895, 139.6917),  # Tokyo, Japan (Northern Hemisphere)
    (-23.5505, -46.6333), # São Paulo, Brazil (Southern Hemisphere)
    (-33.8688, 151.2093), # Sydney, Australia (Southern Hemisphere)
    (-36.8485, 174.7633)  # Auckland, New Zealand (Southern Hemisphere)
]

# Filter out and store only those located in the Southern Hemisphere (latitude < 0)
southern_hemisphere = [coord for coord in coordinates if coord[0] < 0]

# Count the number of coordinates that meet this condition.
count_southern = len(southern_hemisphere)

# Print the results
print(f"Southern Hemisphere coordinates: {southern_hemisphere}")
print(f"Number of coordinates in the Southern Hemisphere: {count_southern}")


Southern Hemisphere coordinates: [(-23.5505, -46.6333), (-33.8688, 151.2093), (-36.8485, 174.7633)]
Number of coordinates in the Southern Hemisphere: 3


## Exercise 20: Generating and Analyzing Random Coordinates

- Write a program that generates random coordinates (latitude between [-90, 90] degrees and longitude between [-180, 180] degrees).
- Use a `while` loop to keep generating coordinates until a pair with both latitude and longitude greater than 50 is generated.
- Print each generated coordinate and the final coordinate that meets the condition.

In [24]:
# Write a program that generates random coordinates (latitude between [-90, 90] degrees and longitude between [-180, 180] degrees).

import random

# Initialize a variable to track the generated coordinates
coordinate = (0, 0)

# Use a while loop to keep generating coordinates until a pair with 'both' latitude and longitude greater than 50 is generated.
while True:
    # Generate random latitude and longitude
    lat = random.uniform(-90, 90)
    lon = random.uniform(-180, 180)

    # Print the generated coordinate
    print(f"Coordinate: ({lat:.4f}, {lon:.4f})")

    # Check if (latitude and longitude) > 50
    if lat > 50 and lon > 50:
        coordinate = (lat, lon)
        break

# Print each generated coordinate and the final coordinate that meets the condition.
print(f"Final Coordinate that meets the condition: ({coordinate[0]:.4f}, {coordinate[1]:.4f})")


Coordinate: (-69.9216, 154.8837)
Coordinate: (75.3796, -14.6337)
Coordinate: (-88.3353, -68.7301)
Coordinate: (46.9077, 0.1174)
Coordinate: (84.2495, -31.3867)
Coordinate: (-39.9375, 168.1000)
Coordinate: (55.1675, 46.5161)
Coordinate: (84.5863, 66.0171)
Final Coordinate that meets the condition: (84.5863, 66.0171)


## Submission Requirements

Complete the exercises above and and upload the notebook to your GitHub repository. Make sure the notebook has a Colab badge at the top so that it can be easily opened in Google Colab. Submit the URL of the notebook to Canvas.